"""The weekly experiment report: machine-readable JSON and a Markdown page a person reads.

Both are generated from the same dictionary :func:`ffdraft.weekly.evaluate.run_weekly_experiment`
returns, so the prose cannot claim a number the JSON does not hold.
"""

from __future__ import annotations

import json
import math
from collections.abc import Mapping
from pathlib import Path
from typing import Any

from ffdraft.timeutil import isoformat_utc, utc_now
from ffdraft.weekly.evaluate import CANDIDATE_ID, MODEL_IDS
from ffdraft.weekly.frozen import (
    DECISION_POOL_DEPTH,
    PROMOTION_RULE,
    WEEKLY_QUANTILE_LEVELS,
    WeeklySpec,
)

__all__ = ["public_report", "report_markdown", "write_report"]

_LABELS = {
    CANDIDATE_ID: "WC1 quantile GBM + conformal (candidate)",
    "b0_season_rate": "B0 season rate",
    "b1_recent_form": "B1 recent form (last 3)",
    "b2_rate_x_vegas": "B2 shrunk rate x implied team total",
}


def public_report(
    result: Mapping[str, Any], *, stage: str, extra: Mapping[str, Any]
) -> dict[str, Any]:
    """The report without the in-memory frames, with provenance attached."""
    body = {key: value for key, value in result.items() if not key.startswith("_")}
    return {
        "report": "weekly_startsit_experiment",
        "stage": stage,
        "generated_at_utc": isoformat_utc(utc_now()),
        "spec": WeeklySpec().to_dict(),
        "configuration_hash": WeeklySpec().configuration_hash(),
        "promotion_rule": PROMOTION_RULE.to_dict(),
        "decision_pool_depth": dict(DECISION_POOL_DEPTH),
        **dict(extra),
        **body,
    }


def _number(value: Any, digits: int = 4) -> str:
    if value is None:
        return "—"
    try:
        number = float(value)
    except (TypeError, ValueError):
        return str(value)
    if math.isnan(number):
        return "—"
    return f"{number:.{digits}f}"


def _metric_table(summary: Mapping[str, Mapping[str, Any]]) -> list[str]:
    lines = [
        "| model | pinball | MAE (median) | pair accuracy | pair Brier "
        "| P10–P90 cover | P25–P75 cover |",
        "|---|---|---|---|---|---|---|",
    ]
    for model_id in MODEL_IDS:
        row = summary[model_id]
        lines.append(
            f"| {_LABELS[model_id]} | {_number(row['pinball'])} | {_number(row['mae_median'], 3)} "
            f"| {_number(row.get('pair_accuracy'))} | {_number(row.get('pair_brier'))} "
            f"| {_number(row['coverage_80'], 3)} | {_number(row['coverage_50'], 3)} |",
        )
    return lines


def report_markdown(report: Mapping[str, Any]) -> str:
    stage = str(report["stage"])
    verdict = report["verdict"]
    title = (
        "Weekly start/sit model — development evaluation"
        if stage == "development"
        else "Weekly start/sit model — sealed 2025 holdout"
    )
    lines = [
        f"# {title}",
        "",
        f"Generated by `ffdraft evaluate-weekly` at {report['generated_at_utc']}. "
        f"Candidate `{CANDIDATE_ID}`, configuration `{report['configuration_hash']}`, rule "
        f"`{verdict['rule']}` (frozen in `src/ffdraft/weekly/frozen.py` before this ran).",
        "",
        f"**Verdict: {'PASS' if verdict['passed'] else 'FAIL'}.**",
        "",
        "## Clauses",
        "",
        "| clause | candidate | comparator | passed |",
        "|---|---|---|---|",
    ]
    for name, clause in verdict["clauses"].items():
        comparator = clause.get("baseline", clause.get("band", clause.get("minimum")))
        if "best_baseline" in clause:
            label = _LABELS.get(clause["best_baseline"], clause["best_baseline"])
            comparator = f"{label} = {_number(clause['baseline'])}"
        candidate = clause.get("candidate", clause.get("wins"))
        lines.append(
            f"| `{name}` | {_number(candidate)} | {comparator} "
            f"| {'yes' if clause['passed'] else 'no'} |"
        )
        if clause.get("bootstrap"):
            boot = clause["bootstrap"]
            lines.append(
                f"| ↳ bootstrap ({boot['clusters']} weeks, {boot['replicates']} reps) | "
                f"{_number(boot['difference'])} "
                f"| [{_number(boot['lower'])}, {_number(boot['upper'])}] | "
                f"{'yes' if boot['lower'] > 0 else 'no'} |",
            )
    lines += ["", "## Pooled", "", *_metric_table(report["pooled"]), ""]
    lines += [
        f"Pairs are every same-position pair in the week's decision pool (top "
        f"{', '.join(f'{k} {v}' for k, v in report['decision_pool_depth'].items())} by B0), "
        f"all three scoring presets. Pinball is macro-averaged over position × preset cells; "
        f"coverage is pooled over rows.",
        "",
        "## By season",
        "",
    ]
    for season, summary in report["by_season"].items():
        lines += [f"### {season}", "", *_metric_table(summary), ""]
    lines += ["## By position", ""]
    for position, summary in report["by_position"].items():
        lines += [f"### {position}", "", *_metric_table(summary), ""]
    lines += [
        "## Start/sit calibration (candidate)",
        "",
        "Pairs binned by the probability the model gave the player it favoured, against how "
        "often that player actually outscored the other.",
        "",
        "| favourite probability | pairs | mean predicted | observed |",
        "|---|---|---|---|",
    ]
    for row in report["diagnostics"]["calibration"]:
        lines.append(
            f"| {row['low']:.2f}–{row['high']:.2f} | {row['pairs']} "
            f"| {_number(row['predicted'], 3)} "
            f"| {_number(row['observed'], 3)} |",
        )
    levels = ", ".join(f"{level:.2f}" for level in WEEKLY_QUANTILE_LEVELS)
    coverage = ", ".join(
        _number(value, 3) for value in report["pooled"][CANDIDATE_ID]["level_coverage"]
    )
    lines += [
        "",
        "## Quantile coverage (candidate)",
        "",
        f"Share of outcomes at or below each quantile. Levels {levels}; observed {coverage}.",
        "",
    ]
    return "\n".join(lines)


def write_report(report: Mapping[str, Any], out_dir: Path, *, name: str) -> list[Path]:
    out_dir.mkdir(parents=True, exist_ok=True)
    json_path = out_dir / f"{name}.json"
    md_path = out_dir / f"{name}.md"
    json_path.write_text(
        json.dumps(report, indent=2, sort_keys=False, default=float) + "\n", encoding="utf-8"
    )
    md_path.write_text(report_markdown(report) + "\n", encoding="utf-8")
    return [json_path, md_path]
